-- Crear extensión pgvector
CREATE EXTENSION IF NOT EXISTS vector;

-- Tabla de documentos con hash único
CREATE TABLE IF NOT EXISTS documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content TEXT NOT NULL,
    source_hash VARCHAR(64) UNIQUE NOT NULL,
    source_document TEXT,
    chunking_strategy VARCHAR(50) DEFAULT 'agentic',
    chunk_index INTEGER,
    char_start INTEGER,
    char_end INTEGER,
    semantic_title VARCHAR(500),
    semantic_summary TEXT,
    semantic_overlap TEXT,
    embedding_model VARCHAR(100),
    metadata_json JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tabla de embeddings con dimensión paramétrica (se reemplazará dinámicamente)
CREATE TABLE IF NOT EXISTS document_embeddings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT REFERENCES documents(id) ON DELETE CASCADE,
    embedding vector(384), -- Se reemplazará dinámicamente
    embedding_type VARCHAR(50) DEFAULT 'content',
    embedding_model VARCHAR(100),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(document_id)
);

-- Índice vectorial
CREATE INDEX IF NOT EXISTS idx_document_embeddings_vector
    ON document_embeddings
    USING ivfflat (embedding vector_cosine_ops)
    WITH (lists = 100);

-- Índices de soporte
CREATE INDEX IF NOT EXISTS idx_documents_source_hash ON documents(source_hash);
CREATE INDEX IF NOT EXISTS idx_documents_strategy_created ON documents(chunking_strategy, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_documents_metadata_jsonb ON documents USING gin(metadata_json);